# Generated by Django 4.1 on 2022-08-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_band_alter_listing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('Creation_Date', models.DateField()),
                ('genre', models.CharField(choices=[('VL', 'Villa'), ('EN', 'Entropeau'), ('GR', 'Garage'), ('LC', 'Lycee'), ('UN', 'University'), ('BTN', 'Batiment R Plus 3')], max_length=50)),
                ('nombre_scoiter', models.IntegerField()),
            ],
        ),
    ]
