# Generated by Django 4.1 on 2022-08-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_siege_nombre_scoiter_siege_number_scoiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='siege',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.siege'),
        ),
    ]
