# Generated by Django 4.1 on 2022-08-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_band_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('Ml', 'Male'), ('FM', 'Female'), ('OT', 'Other')], max_length=15)),
                ('contry', models.CharField(choices=[('+235', 'Tchad'), ('+33', 'France'), ('+1', 'Usa'), ('+001', 'Canada'), ('+010', 'Chine')], max_length=25)),
                ('borned', models.DateField(null=True)),
                ('nationality', models.CharField(max_length=25)),
                ('job', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='siege',
            name='genre',
            field=models.CharField(choices=[('VL', 'Villa'), ('EN', 'Entropeau'), ('GR', 'Garage'), ('LC', 'Lycee'), ('UN', 'University'), ('BTN', 'Batiment')], max_length=100),
        ),
    ]
