# Generated by Django 4.1 on 2022-08-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
